#' Generates a list of PubMed results based on a UniProt ID and a user-defined keyword.
#'
#' @param df R dataframe having 5 attributes, UniProtID, IDType, TaxID, Keyword, KeywordInTitleOnly.
#' @param output.file Path string to the location to write the output file with the summarised results of the Pubmed query. Default = NULL gives no .xls summary file written out.
#' @param plots.dir Path to the directory where the plots generated by the package will be saved.Default = NULL gives no plots saved to disk.
#' @return Generates an Excel file \code{output.file} with Pubmed query results using the UniProt identifers and keyword search in \code{query.file}.
#' @examples
#' omixLitMiner(potentialmarker, output.file = "potential_marker_pubmed_results.xlsx", plots.dir = 'plots')'
#' df <- readWorkbook(system.file("extdata", "input_uniprot_keywords.xlsx", package="OmixLitMiner"))
#' omixLitMiner(df, output.file = "potential_marker_pubmed_results.xlsx", , plots.dir = 'plots')
#' @export
omixLitMiner <- function(df, output.file = NULL, plots.dir = NULL) {
  list.datquery = list()
  list.datpubmed = list()
  cat(plots.dir)
  print('BOL HARI......')

  # create progress bar
  pb <- txtProgressBar(min = 0, max = nrow(df), style = 3)
  
  if (!is.null(output.file)) {
    output.file.dir <- dirname(output.file)
    output_dir <- file.path(output.file.dir)
    if (!dir.exists(output_dir)) {
      dir.create(output_dir)
    }
  }

  for(query.idx in 1:nrow(df)) {
    Sys.sleep(0.1)
    UniProtID = df[query.idx, 'UniProtID']
    IDType = df[query.idx, "IDType"]
    taxid = df[query.idx, 'TaxID']
    keyword =  df[query.idx, 'Keyword']
    ti.only = df[query.idx,5]

    pd.res <- try(omix_miner(UniProtID, IDType, taxid, keyword, ti.only, query.idx=query.idx, plots.dir))

    if(!inherits(pd.res, 'try-error')) {

      list.datquery[[query.idx]] = pd.res$dat.query
      list.datpubmed[[query.idx]] = pd.res$dat.pubmed

    } else {
      synonyms <- NULL
      list.datquery[[query.idx]] = data.frame('UniProtID'=UniProtID, 'GeneID' = NA, 'TaxID'=taxid, 'Synonyms' = paste(synonyms, collapse=','),
        'Keywords' = keyword, 'KeywordInTitleOnly'=ti.only, 'TotalResults'=0,
        'Category' = 3, 'False' = 0, 'PubmedQuery'=NA)

      list.datpubmed[[query.idx]] = 'No result'

    }
    # update progress bar
    setTxtProgressBar(pb, query.idx)
  }

  all.datquery = do.call(rbind, list.datquery)
  all.datquery$NQuery = 1:nrow(all.datquery)
  all.datquery = all.datquery[,c(ncol(all.datquery),1:(ncol(all.datquery)-1))]

  all.datquery[is.na(all.datquery)] = ''
  # output

  wb = openxlsx::createWorkbook()

  openxlsx::addWorksheet(wb, sheetName="query")

  openxlsx::writeData(wb,"query", all.datquery)

  for(ii in 1:length(list.datpubmed) ) {

    list.datquery[[ii]][is.na(list.datquery[[ii]])] = ''

    openxlsx::addWorksheet(wb, sheetName=paste("pubmed result", ii) )
    openxlsx::writeData(wb, paste("pubmed result", ii), list.datquery[[ii]])
    openxlsx::writeData(wb, paste("pubmed result", ii), list.datpubmed[[ii]], startRow=4)
    cat(paste(plots.dir, 'barplotNwordcloud', ii, '.png', sep=''))
    if(file.exists(paste(plots.dir, 'barplotNwordcloud', ii, '.png', sep='') ) )
      openxlsx::insertImage(wb, paste("pubmed result", ii), paste('barplotNwordcloud', ii, '.png', sep=''),
        width=5, height=8, startRow = 3, startCol=12)

    if(file.exists(paste(plots.dir, 'plot_dist_mesh', ii, '.png', sep='') ) )
      openxlsx::insertImage(wb, paste("pubmed result", ii), paste('plot_dist_mesh', ii, '.png', sep=''),
        width=5, height=5, startRow = 3, startCol=20)
  }
  
  if (!is.null(output.file)) {
      openxlsx::saveWorkbook(wb, output.file, overwrite=T)
  }

  invisible(list(summary_results=all.datquery, pubmed_results=list.datpubmed))
}






